version: '3.8'

services:
  jaahub-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
      - "8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal\SQLEXPRESS;Database=Jaahub;Trusted_Connection=True;MultipleActiveResultSets=true;TrustServerCertificate=True
    networks:
      - jaahub-network

networks:
  jaahub-network:
    driver: bridge
